/*
Organization structure API

Welcome on the documentation for the Organization Structure API


The version of the OpenAPI document: 1.0
Contact: developers@lucca.fr

NOTE: This file is auto generated by Konfig (https://konfigthis.com).
*/

import { AxiosRequestConfig } from "axios";
import {
  AxisSectionsApi,
  DepartmentsApi,
} from "./api";
import { Configuration, ConfigurationParameters } from "./configuration";
import { LuccaOrganizationCustom } from "./client-custom";

export class LuccaOrganization extends LuccaOrganizationCustom {
  readonly axisSections: AxisSectionsApi;
  readonly departments: DepartmentsApi;

  constructor(configurationParameters: ConfigurationParameters) {
    super(configurationParameters);
    const configuration = new Configuration(configurationParameters);
    this.axisSections = new AxisSectionsApi(configuration);
    this.departments = new DepartmentsApi(configuration);
  }

}
