/*
Organization structure API

Welcome on the documentation for the Organization Structure API


The version of the OpenAPI document: 1.0
Contact: developers@lucca.fr

NOTE: This file is auto generated by Konfig (https://konfigthis.com).
*/
import type * as buffer from "buffer"

import { AxisAllOf } from './axis-all-of';
import { AxisTreeless } from './axis-treeless';

/**
 * @type Axis
 * Read more about axes in the [definition for the axisSection resource](reference/Organization-v3.yaml/components/schemas/AxisSection).
 * @export
 */
export type Axis = AxisAllOf & AxisTreeless;


