/*
Organization structure API

Welcome on the documentation for the Organization Structure API


The version of the OpenAPI document: 1.0
Contact: developers@lucca.fr

NOTE: This file is auto generated by Konfig (https://konfigthis.com).
*/
import type * as buffer from "buffer"

import { AxissectionsList200ResponseData } from './axissections-list200-response-data';

/**
 * 
 * @export
 * @interface AxissectionsList200Response
 */
export interface AxissectionsList200Response {
    /**
     * 
     * @type {AxissectionsList200ResponseData}
     * @memberof AxissectionsList200Response
     */
    'data'?: AxissectionsList200ResponseData;
}

