/*
Organization structure API

Welcome on the documentation for the Organization Structure API


The version of the OpenAPI document: 1.0
Contact: developers@lucca.fr

NOTE: This file is auto generated by Konfig (https://konfigthis.com).
*/
import type * as buffer from "buffer"

import { Axis } from './axis';

/**
 * 
 * @export
 * @interface AxissectionsListResponseData
 */
export interface AxissectionsListResponseData {
    /**
     * 
     * @type {Array<Axis>}
     * @memberof AxissectionsListResponseData
     */
    'items'?: Array<Axis>;
}

