/*
Organization structure API

Welcome on the documentation for the Organization Structure API


The version of the OpenAPI document: 1.0
Contact: developers@lucca.fr

NOTE: This file is auto generated by Konfig (https://konfigthis.com).
*/
import type * as buffer from "buffer"

import { AxisSectionTreeless } from './axis-section-treeless';

/**
 * 
 * @export
 * @interface AxisSectionAllOf
 */
export interface AxisSectionAllOf {
    /**
     * 
     * @type {Array<AxisSectionTreeless>}
     * @memberof AxisSectionAllOf
     */
    'parentAxisSections'?: Array<AxisSectionTreeless>;
    /**
     * 
     * @type {Array<AxisSectionTreeless>}
     * @memberof AxisSectionAllOf
     */
    'childrenAxisSections'?: Array<AxisSectionTreeless>;
}

