/*
Organization structure API

Welcome on the documentation for the Organization Structure API


The version of the OpenAPI document: 1.0
Contact: developers@lucca.fr

NOTE: This file is auto generated by Konfig (https://konfigthis.com).
*/
import type * as buffer from "buffer"


/**
 * 
 * @export
 * @interface AxisSectionTreeless
 */
export interface AxisSectionTreeless {
    /**
     * 
     * @type {any}
     * @memberof AxisSectionTreeless
     */
    'description'?: any;
    /**
     * 
     * @type {number}
     * @memberof AxisSectionTreeless
     */
    'id'?: number;
    /**
     * 
     * @type {string}
     * @memberof AxisSectionTreeless
     */
    'name'?: string;
    /**
     * 
     * @type {string}
     * @memberof AxisSectionTreeless
     */
    'url'?: string;
    /**
     * 
     * @type {string}
     * @memberof AxisSectionTreeless
     */
    'code': string;
    /**
     * 
     * @type {string}
     * @memberof AxisSectionTreeless
     */
    'multilingualName': string;
    /**
     * 
     * @type {any}
     * @memberof AxisSectionTreeless
     */
    'ownerId'?: any;
    /**
     * 
     * @type {any}
     * @memberof AxisSectionTreeless
     */
    'startOn'?: any;
    /**
     * 
     * @type {any}
     * @memberof AxisSectionTreeless
     */
    'endOn'?: any;
    /**
     * 
     * @type {boolean}
     * @memberof AxisSectionTreeless
     */
    'active'?: boolean;
    /**
     * 
     * @type {number}
     * @memberof AxisSectionTreeless
     */
    'axisId': number;
}

