/*
Organization structure API

Welcome on the documentation for the Organization Structure API


The version of the OpenAPI document: 1.0
Contact: developers@lucca.fr

NOTE: This file is auto generated by Konfig (https://konfigthis.com).
*/
import type * as buffer from "buffer"

import { DepartmentTreeNodeNode } from './department-tree-node-node';

/**
 * 
 * @export
 * @interface DepartmentTreeNode
 */
export interface DepartmentTreeNode {
    /**
     * 
     * @type {DepartmentTreeNodeNode}
     * @memberof DepartmentTreeNode
     */
    'node'?: DepartmentTreeNodeNode;
    /**
     * List of all children departments.
     * @type {Array<DepartmentTreeNode>}
     * @memberof DepartmentTreeNode
     */
    'children'?: Array<DepartmentTreeNode>;
}

