/*
Organization structure API

Welcome on the documentation for the Organization Structure API


The version of the OpenAPI document: 1.0
Contact: developers@lucca.fr

NOTE: This file is auto generated by Konfig (https://konfigthis.com).
*/
import type * as buffer from "buffer"

import { Department } from './department';

/**
 * 
 * @export
 * @interface DepartmentsGetAllResponseData
 */
export interface DepartmentsGetAllResponseData {
    /**
     * 
     * @type {Array<Department>}
     * @memberof DepartmentsGetAllResponseData
     */
    'items'?: Array<Department>;
}

