/*
Organization structure API

Welcome on the documentation for the Organization Structure API


The version of the OpenAPI document: 1.0
Contact: developers@lucca.fr

NOTE: This file is auto generated by Konfig (https://konfigthis.com).
*/
import type * as buffer from "buffer"


/**
 * 
 * @export
 * @interface DepartmentTreeNodeNode
 */
export interface DepartmentTreeNodeNode {
    /**
     * Department id
     * @type {number}
     * @memberof DepartmentTreeNodeNode
     */
    'id'?: number;
    /**
     * Department name
     * @type {string}
     * @memberof DepartmentTreeNodeNode
     */
    'name'?: string;
    /**
     * Department URL
     * @type {string}
     * @memberof DepartmentTreeNodeNode
     */
    'url'?: string;
}

