/*
Organization structure API

Welcome on the documentation for the Organization Structure API


The version of the OpenAPI document: 1.0
Contact: developers@lucca.fr

NOTE: This file is auto generated by Konfig (https://konfigthis.com).
*/
import type * as buffer from "buffer"


/**
 * 
 * @export
 * @interface DepartmentsGetAll400Response
 */
export interface DepartmentsGetAll400Response {
    /**
     * 
     * @type {number}
     * @memberof DepartmentsGetAll400Response
     */
    'Status'?: number;
    /**
     * 
     * @type {string}
     * @memberof DepartmentsGetAll400Response
     */
    'Message'?: string;
}

