/*
Organization structure API

Welcome on the documentation for the Organization Structure API


The version of the OpenAPI document: 1.0
Contact: developers@lucca.fr

NOTE: This file is auto generated by Konfig (https://konfigthis.com).
*/
import type * as buffer from "buffer"

import { DepartmentTreeNode } from './department-tree-node';
import { Null } from './null';

/**
 * 
 * @export
 * @interface DepartmentsListTreeResponseData
 */
export interface DepartmentsListTreeResponseData {
    /**
     * Root department. Always null.
     * @type {Null}
     * @memberof DepartmentsListTreeResponseData
     */
    'node'?: Null;
    /**
     * Max depth: 9 levels
     * @type {Array<DepartmentTreeNode>}
     * @memberof DepartmentsListTreeResponseData
     */
    'children'?: Array<DepartmentTreeNode>;
}

