/*
Organization structure API

Welcome on the documentation for the Organization Structure API


The version of the OpenAPI document: 1.0
Contact: developers@lucca.fr

NOTE: This file is auto generated by Konfig (https://konfigthis.com).
*/
import type * as buffer from "buffer"

import { DepartmentsGetAllResponseData } from './departments-get-all-response-data';

/**
 * 
 * @export
 * @interface DepartmentsGetAllResponse
 */
export interface DepartmentsGetAllResponse {
    /**
     * 
     * @type {DepartmentsGetAllResponseData}
     * @memberof DepartmentsGetAllResponse
     */
    'data'?: DepartmentsGetAllResponseData;
}

